// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RifaManager.Infrastructure.Context;

#nullable disable

namespace RifaManager.Infrastructure.Migrations
{
    [DbContext(typeof(RifaDbContext))]
    [Migration("20260606105445_AddUsuarioSenha")]
    partial class AddUsuarioSenha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RifaManager.Domain.Entities.Bilhete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CanceladoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PagoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RifaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioResponsavelId");

                    b.HasIndex("RifaId", "Numero")
                        .IsUnique();

                    b.ToTable("Bilhetes");
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("Telefone");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Rifa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataSorteio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Encerrada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Premio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorBilhete")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSorteio");

                    b.HasIndex("Nome");

                    b.ToTable("Rifas");
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            Email = "admin@rifamanager.local",
                            Nome = "Administrador",
                            Perfil = 2,
                            Senha = "pbkdf2_sha256$100000$cmlmYS1tYW5hZ2VyLWFkbWluLXNhbHQ=$Jwh4dZlB22rYR5uoofn97Y7FJwdnwOdI8KF8NzjssEM="
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            Email = "usuario@rifamanager.local",
                            Nome = "Usuario Comum",
                            Perfil = 1,
                            Senha = "pbkdf2_sha256$100000$cmlmYS1tYW5hZ2VyLXVzZXItc2FsdA==$+cik2bvSeHUEaI/Mp22vmzb9ZZ+KwN/p/F63xTDcWVg="
                        });
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Bilhete", b =>
                {
                    b.HasOne("RifaManager.Domain.Entities.Participante", "Participante")
                        .WithMany("Bilhetes")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RifaManager.Domain.Entities.Rifa", "Rifa")
                        .WithMany("Bilhetes")
                        .HasForeignKey("RifaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RifaManager.Domain.Entities.Usuario", "UsuarioResponsavel")
                        .WithMany("BilhetesVendidos")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Rifa");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Participante", b =>
                {
                    b.Navigation("Bilhetes");
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Rifa", b =>
                {
                    b.Navigation("Bilhetes");
                });

            modelBuilder.Entity("RifaManager.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("BilhetesVendidos");
                });
#pragma warning restore 612, 618
        }
    }
}
